url: https://cubio.soc.srcf.net
baseurl: /home/

# Site settings
title: Cambridge University Biological Society
email: your-email@domain.com
description: "The Cambridge University Biological Society (BioSoc) is a science society dedicated to bringing the finest speakers to Cambridge."


# Team names, titles and social links
people:
- name: Lawrence Ng
  pic: Lawrence
  position: President
  year: 3rd
  subject: Natural Sciences (Biological)
  college: St John's

- name: Nausicaa Ng
  pic: 1
  position: Vice-President
  year: 3rd
  subject: Natural Sciences (Biological)
  college: Lucy Cavendish

- name: Peter Parker
  pic: Peter_serious
  position: Secretary
  year: 3rd
  subject: Natural Sciences (Biological)
  college: Selwyn

- name: Dayoun Moon
  pic: Dayoun
  position: Treasurer
  year: 2nd
  subject: Natural Sciences (Biological)
  college: Sidney Sussex

- name: Rosalyn Cheng
  pic: Rosalyn
  position: Speaker's Officer
  year: 2nd
  subject: Medicine
  college: Newnham

- name: Cassandra Lui
  pic: Cassandra
  position: Events Officer
  year: 2nd
  subject: Natural Sciences (Biological)
  college: Selwyn

- name: Monica Simpson
  pic: 2
  position: Social Officer
  year: 3rd
  subject: Natural Sciences (Biological)
  college: Selwyn

- name: Samuel Li
  pic: 3
  position: Webmaster
  year: 2nd
  subject: Natural Sciences (Biological)
  college: St John's

- name: Tuna Akyol
  pic: 1
  position: Sponsorship Officer
  year: 3rd
  subject: Natural Sciences (Biological)
  college: Caius


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/biosoc.cam

# Postal address (add as many lines as necessary)
address:
  - line: The Old Schools, Trinity Lane
  - line: Cambridge CB2 1TP

# Build settings
markdown: kramdown
permalink: pretty
future: true