url: https://cubio.soc.srcf.net
baseurl: /home/

# Site settings
title: Cambridge University Biological Society
email: your-email@domain.com
description: "The Cambridge University Biological Society (BioSoc) is a science society dedicated to bringing the finest speakers to Cambridge."


# Team names, titles and social links
people:
- name: Lawrence Ng
  pic: 1
  position: President

- name: Nausicaa Ng
  pic: 2
  position: Vice-President

- name: Peter Parker
  pic: 3
  position: Secretary

- name: Cassandra Lui
  pic: 1
  position: Events Officer

- name: Monica Simpson
  pic: 2
  position: Social Officer

- name: Samuel Li
  pic: 3
  position: Webmaster

- name: Tuna Akyol
  pic: 1
  position: Sponsorship Officer


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/biosoc.cam

# Postal address (add as many lines as necessary)
address:
  - line: The Old Schools, Trinity Lane
  - line: Cambridge CB2 1TP

# Build settings
markdown: kramdown
permalink: pretty